name: Cypress and cucumber tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Prepare report  
        run: |
            mkdir -p reports
            mv cucumber-report.html reports/index.html
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: reports
      - name: Print Report Link
        run: |
          echo "Report: https://mariana-zaozirna.github.io/cy_cucumber/index.html" >> $GITHUB_STEP_SUMMARY
          